### PR TITLE
Entities

### PR DESCRIPTION
**Pull request by Aryevang**
Adding the base skeleton of the entities.

### CODE REVIEW

**Comment by reynoldmorel** [comment]
Looks like we have 10 changes where most of them are entities. Could we separate into different PRs, 1 PR per entity could be. Let's try to commit things in one context. Let's say for example:
```
You can create a commit for Inventory and InventoryItem
Also you can add a small doc in the readme file explaining the purpose of these 2 classes.
Also you give UML diagram of these 2 classes
```

The idea is that it should be easy for anyone to understan the progress of your commits, and understand how this is scaling.

**Review by reynoldmorel — CHANGES_REQUESTED** [review]
Please separate in different PRs

**Comment by reynoldmorel** [comment]
One more thing, in your commit history, please avoid having unwanted commits going into master like: `9ea9363329d2cad416377416bc1fdf0283341e59` or `e064eaa75e55a0735144400a527445c1ad653d4e`

`squash` your commits using `git rebase`
also you can use `git commit --ammend` after your first commit

**Comment by Aryevang** [comment]
This PR is going to be substituted by other PRs with an incremental evolution.

**Pull request closed without merging**
